spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  thymeleaf:
    cache: false

industry:
  np: 1
  pn: 1
  pz: 965
  fs: m:90+t:2
  fields: f12,f14

stock:
  np: 1
  pn: 1
  pz: 965
  fields: f12,f14

industryKLine:
  fields1: f1,f3
  fields2: f59
  fqt: 1
  end: 20500101
  lmt: 1

stockKLine:
  fields1: f1,f3
  fields2: f56,f57,f59
  fqt: 1
  end: 20500101
  lmt: 1
